use Test::More tests => 85;
use warnings;
use strict;
use Graphics::TIFF ':all';
BEGIN { use_ok('Graphics::TIFF') }

#########################

is( TIFFTAG_IMAGEWIDTH,  256, "TIFFTAG_IMAGEWIDTH" );
is( TIFFTAG_IMAGELENGTH, 257, "TIFFTAG_IMAGELENGTH" );

is( TIFFTAG_BITSPERSAMPLE,     258,   'TIFFTAG_BITSPERSAMPLE' );
is( TIFFTAG_COMPRESSION,       259,   'TIFFTAG_COMPRESSION' );
is( COMPRESSION_NONE,          1,     'COMPRESSION_NONE' );
is( COMPRESSION_CCITTRLE,      2,     'COMPRESSION_CCITTRLE' );
is( COMPRESSION_CCITTFAX3,     3,     'COMPRESSION_CCITTFAX3' );
is( COMPRESSION_CCITT_T4,      3,     'COMPRESSION_CCITT_T4' );
is( COMPRESSION_CCITTFAX4,     4,     'COMPRESSION_CCITTFAX4' );
is( COMPRESSION_CCITT_T6,      4,     'COMPRESSION_CCITT_T6' );
is( COMPRESSION_LZW,           5,     'COMPRESSION_LZW' );
is( COMPRESSION_OJPEG,         6,     'COMPRESSION_OJPEG' );
is( COMPRESSION_JPEG,          7,     'COMPRESSION_JPEG' );
is( COMPRESSION_T85,           9,     'COMPRESSION_T85' );
is( COMPRESSION_T43,           10,    'COMPRESSION_T43' );
is( COMPRESSION_NEXT,          32766, 'COMPRESSION_NEXT' );
is( COMPRESSION_CCITTRLEW,     32771, 'COMPRESSION_CCITTRLEW' );
is( COMPRESSION_PACKBITS,      32773, 'COMPRESSION_PACKBITS' );
is( COMPRESSION_THUNDERSCAN,   32809, 'COMPRESSION_THUNDERSCAN' );
is( COMPRESSION_IT8CTPAD,      32895, 'COMPRESSION_IT8CTPAD' );
is( COMPRESSION_IT8LW,         32896, 'COMPRESSION_IT8LW' );
is( COMPRESSION_IT8MP,         32897, 'COMPRESSION_IT8MP' );
is( COMPRESSION_IT8BL,         32898, 'COMPRESSION_IT8BL' );
is( COMPRESSION_PIXARFILM,     32908, 'COMPRESSION_PIXARFILM' );
is( COMPRESSION_PIXARLOG,      32909, 'COMPRESSION_PIXARLOG' );
is( COMPRESSION_DEFLATE,       32946, 'COMPRESSION_DEFLATE' );
is( COMPRESSION_ADOBE_DEFLATE, 8,     'COMPRESSION_ADOBE_DEFLATE' );
is( COMPRESSION_DCS,           32947, 'COMPRESSION_DCS' );
is( COMPRESSION_JBIG,          34661, 'COMPRESSION_JBIG' );
is( COMPRESSION_SGILOG,        34676, 'COMPRESSION_SGILOG' );
is( COMPRESSION_SGILOG24,      34677, 'COMPRESSION_SGILOG24' );
is( COMPRESSION_JP2000,        34712, 'COMPRESSION_JP2000' );
is( COMPRESSION_LZMA,          34925, 'COMPRESSION_LZMA' );

is( TIFFTAG_PHOTOMETRIC,    262,   'TIFFTAG_PHOTOMETRIC' );
is( PHOTOMETRIC_MINISWHITE, 0,     'PHOTOMETRIC_MINISWHITE' );
is( PHOTOMETRIC_MINISBLACK, 1,     'PHOTOMETRIC_MINISBLACK' );
is( PHOTOMETRIC_RGB,        2,     'PHOTOMETRIC_RGB' );
is( PHOTOMETRIC_PALETTE,    3,     'PHOTOMETRIC_PALETTE' );
is( PHOTOMETRIC_MASK,       4,     'PHOTOMETRIC_MASK' );
is( PHOTOMETRIC_SEPARATED,  5,     'PHOTOMETRIC_SEPARATED' );
is( PHOTOMETRIC_YCBCR,      6,     'PHOTOMETRIC_YCBCR' );
is( PHOTOMETRIC_CIELAB,     8,     'PHOTOMETRIC_CIELAB' );
is( PHOTOMETRIC_ICCLAB,     9,     'PHOTOMETRIC_ICCLAB' );
is( PHOTOMETRIC_ITULAB,     10,    'PHOTOMETRIC_ITULAB' );
is( PHOTOMETRIC_LOGL,       32844, 'PHOTOMETRIC_LOGL' );
is( PHOTOMETRIC_LOGLUV,     32845, 'PHOTOMETRIC_LOGLUV' );

is( TIFFTAG_FILLORDER, 266, "TIFFTAG_FILLORDER" );
is( FILLORDER_MSB2LSB, 1,   "FILLORDER_MSB2LSB" );
is( FILLORDER_LSB2MSB, 2,   "FILLORDER_LSB2MSB" );

is( TIFFTAG_IMAGEDESCRIPTION, 270, 'TIFFTAG_IMAGEDESCRIPTION' );
is( TIFFTAG_STRIPOFFSETS,     273, 'TIFFTAG_STRIPOFFSETS' );
is( TIFFTAG_SAMPLESPERPIXEL,  277, 'TIFFTAG_SAMPLESPERPIXEL' );
is( TIFFTAG_ROWSPERSTRIP,     278, "TIFFTAG_ROWSPERSTRIP" );
is( TIFFTAG_STRIPBYTECOUNTS,  279, "TIFFTAG_STRIPBYTECOUNTS" );

is( TIFFTAG_XRESOLUTION,  282, "TIFFTAG_XRESOLUTION" );
is( TIFFTAG_YRESOLUTION,  283, "TIFFTAG_YRESOLUTION" );
is( TIFFTAG_PLANARCONFIG, 284, "TIFFTAG_PLANARCONFIG" );
is( PLANARCONFIG_CONTIG,  1,   "PLANARCONFIG_CONTIG" );

is( TIFFTAG_GROUP3OPTIONS,  292, 'TIFFTAG_GROUP3OPTIONS' );
is( TIFFTAG_T4OPTIONS,      292, 'TIFFTAG_T4OPTIONS' );
is( GROUP3OPT_2DENCODING,   0x1, 'GROUP3OPT_2DENCODING' );
is( GROUP3OPT_UNCOMPRESSED, 0x2, 'GROUP3OPT_UNCOMPRESSED' );
is( GROUP3OPT_FILLBITS,     0x4, 'GROUP3OPT_FILLBITS' );

is( TIFFTAG_GROUP4OPTIONS,  293, 'TIFFTAG_GROUP4OPTIONS' );
is( TIFFTAG_T6OPTIONS,      293, 'TIFFTAG_T6OPTIONS' );
is( GROUP4OPT_UNCOMPRESSED, 0x2, 'GROUP4OPT_UNCOMPRESSED' );

is( TIFFTAG_RESOLUTIONUNIT, 296, 'TIFFTAG_RESOLUTIONUNIT' );
is( RESUNIT_NONE,           1,   'RESUNIT_NONE' );
is( RESUNIT_INCH,           2,   'RESUNIT_INCH' );
is( RESUNIT_CENTIMETER,     3,   'RESUNIT_CENTIMETER' );

is( TIFFTAG_PAGENUMBER, 297, "TIFFTAG_PAGENUMBER" );

is( TIFFTAG_PREDICTOR,       317, 'TIFFTAG_PREDICTOR' );
is( PREDICTOR_NONE,          1,   'PREDICTOR_NONE' );
is( PREDICTOR_HORIZONTAL,    2,   'PREDICTOR_HORIZONTAL' );
is( PREDICTOR_FLOATINGPOINT, 3,   'PREDICTOR_FLOATINGPOINT' );

is( TIFFTAG_COLORMAP, 320, 'TIFFTAG_COLORMAP' );

is( TIFFTAG_OPIIMAGEID, 32781, 'TIFFTAG_OPIIMAGEID' );

is( TIFFTAG_EXIFIFD, 34665, "TIFFTAG_EXIFIFD" );

is( TIFFPRINT_STRIPS,       1,     "TIFFPRINT_STRIPS" );
is( TIFFPRINT_CURVES,       2,     "TIFFPRINT_CURVES" );
is( TIFFPRINT_COLORMAP,     4,     "TIFFPRINT_COLORMAP" );
is( TIFFPRINT_JPEGQTABLES,  0x100, "TIFFPRINT_JPEGQTABLES" );
is( TIFFPRINT_JPEGACTABLES, 0x200, "TIFFPRINT_JPEGACTABLES" );
is( TIFFPRINT_JPEGDCTABLES, 0x200, "TIFFPRINT_JPEGDCTABLES" );
