use Test::More tests => 7;
use warnings;
use strict;
BEGIN { use_ok('Graphics::TIFF') };

#########################

is (TIFFTAG_IMAGEWIDTH,  256, "TIFFTAG_IMAGEWIDTH");
is (TIFFTAG_IMAGELENGTH, 257, "TIFFTAG_IMAGELENGTH");
is (TIFFTAG_ROWSPERSTRIP, 278, "TIFFTAG_ROWSPERSTRIP");
is (TIFFTAG_PLANARCONFIG, 284, "TIFFTAG_PLANARCONFIG");
is (PLANARCONFIG_CONTIG, 1, "PLANARCONFIG_CONTIG");

is (TIFFTAG_EXIFIFD, 34665, "TIFFTAG_EXIFIFD");
